using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AutoAssert.Generator;

/// <summary>
/// Generates a reflection-free equivalency comparer for every type annotated with
/// <c>[AutoAssert.GenerateEquivalencyComparer]</c>, and registers it with
/// <c>AutoAssert.GeneratedEquivalencyRegistry</c> via a module initializer so
/// <c>BeEquivalentTo</c> picks it up automatically — no reflection, no manual wiring.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class EquivalencyComparerGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "AutoAssert.GenerateEquivalencyComparerAttribute";

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace AutoAssert
        {
            /// <summary>
            /// Marks a type for compile-time equivalency comparer generation: AutoAssert.Generator
            /// emits a reflection-free comparer for this type and registers it so
            /// <c>BeEquivalentTo</c> uses it automatically whenever both sides are this exact type.
            /// </summary>
            [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, Inherited = false)]
            public sealed class GenerateEquivalencyComparerAttribute : System.Attribute
            {
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("GenerateEquivalencyComparerAttribute.g.cs", AttributeSource));

        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
                AttributeFullName,
                static (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
                static (ctx, _) => ctx.TargetSymbol)
            .Collect();

        context.RegisterSourceOutput(candidates, static (spc, types) =>
        {
            foreach (var type in types.Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>())
            {
                if (type.ContainingType is not null || type.IsGenericType)
                {
                    // Nested and generic types are out of scope for this MVP generator —
                    // BeEquivalentTo silently falls back to the reflection-based engine for them.
                    continue;
                }

                var source = GenerateComparerSource(type);
                if (source is not null)
                {
                    spc.AddSource($"{type.Name}.AutoAssertEquivalencyComparer.g.cs", source);
                }
            }
        });
    }

    private static string? GenerateComparerSource(INamedTypeSymbol type)
    {
        var members = GetComparableMembers(type);
        if (members.Count == 0)
        {
            return null;
        }

        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        var typeName = type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat.WithMemberOptions(SymbolDisplayMemberOptions.None));
        var qualifiedTypeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var comparerClassName = $"{type.Name}_AutoAssertEquivalencyComparer";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();

        if (ns is not null)
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    /// <summary>Compile-time-generated, reflection-free equivalency comparer for <see cref=\"{typeName}\"/>.</summary>");
        sb.AppendLine($"    internal static class {comparerClassName}");
        sb.AppendLine("    {");
        sb.AppendLine("        [ModuleInitializer]");
        sb.AppendLine("        public static void Register()");
        sb.AppendLine("        {");
        sb.AppendLine($"            global::AutoAssert.GeneratedEquivalencyRegistry.Register(typeof({qualifiedTypeName}), (a, e, path, options, failures) => Compare(({qualifiedTypeName})a, ({qualifiedTypeName})e, path, options, failures));");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public static bool Compare({qualifiedTypeName} actual, {qualifiedTypeName} expected, string path, global::AutoAssert.EquivalencyOptions options, List<string> failures)");
        sb.AppendLine("        {");
        sb.AppendLine("            var ok = true;");

        foreach (var member in members)
        {
            sb.AppendLine();
            sb.AppendLine($"            if (!options.IsExcluded(\"{member.Name}\"))");
            sb.AppendLine("            {");

            if (member.IsSimple)
            {
                sb.AppendLine($"                if (!global::System.Collections.Generic.EqualityComparer<{member.TypeName}>.Default.Equals(actual.{member.Name}, expected.{member.Name}))");
                sb.AppendLine("                {");
                sb.AppendLine($"                    failures.Add(global::AutoAssert.GeneratedEquivalencyHelpers.BuildMismatchMessage(global::AutoAssert.GeneratedEquivalencyHelpers.AppendPath(path, \"{member.Name}\"), expected.{member.Name}, actual.{member.Name}));");
                sb.AppendLine("                    ok = false;");
                sb.AppendLine("                }");
            }
            else
            {
                sb.AppendLine($"                if (!global::AutoAssert.GeneratedEquivalencyHelpers.CompareValue(actual.{member.Name}, expected.{member.Name}, global::AutoAssert.GeneratedEquivalencyHelpers.AppendPath(path, \"{member.Name}\"), options, failures))");
                sb.AppendLine("                {");
                sb.AppendLine("                    ok = false;");
                sb.AppendLine("                }");
            }

            sb.AppendLine("            }");
        }

        sb.AppendLine();
        sb.AppendLine("            return ok;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        if (ns is not null)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static List<ComparableMember> GetComparableMembers(INamedTypeSymbol type)
    {
        var members = new List<ComparableMember>();

        foreach (var member in type.GetMembers())
        {
            switch (member)
            {
                case IPropertySymbol { DeclaredAccessibility: Accessibility.Public, IsStatic: false, IsIndexer: false, GetMethod.DeclaredAccessibility: Accessibility.Public } property:
                    members.Add(new ComparableMember(property.Name, property.Type, IsSimpleType(property.Type)));
                    break;
                case IFieldSymbol { DeclaredAccessibility: Accessibility.Public, IsStatic: false, IsConst: false } field:
                    members.Add(new ComparableMember(field.Name, field.Type, IsSimpleType(field.Type)));
                    break;
            }
        }

        return members;
    }

    private static bool IsSimpleType(ITypeSymbol type)
    {
        // Mirrors AutoAssert's runtime IsSimple(Type) classification: any value type (including
        // enums and Nullable<T> of one), plus string, are compared via direct equality; anything
        // else (reference types, collections) recurses through GeneratedEquivalencyHelpers.
        return type.IsValueType || type.SpecialType == SpecialType.System_String;
    }

    private sealed class ComparableMember
    {
        public ComparableMember(string name, ITypeSymbol type, bool isSimple)
        {
            Name = name;
            Type = type;
            IsSimple = isSimple;
        }

        public string Name { get; }

        public ITypeSymbol Type { get; }

        public bool IsSimple { get; }

        public string TypeName => Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }
}
